### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by makitso** [osolgithub/OSOLCaptcha4Joomla3#4]
Installed v3 of Captcha from this site.  Running in Joomla 3.4.3.  Everything works OK for the end.  However, when loading admin page there is a wrong URL for the .css file.  

The link file below has the administrator in the path.  The subject file is not under /administrator but /plugins.
  <link rel="stylesheet" href="http://localhost/administrator/plugins/system/osolcaptcha/osolCaptcha/captchaStyle.css" type="text/css" />

**Comment by osolgithub** [comment]
Hello Makitso,

Thanks for pointing out the bug, the issue is fixed now. Please download the latest version form github and let me know if you find any further issues

thanks

Sreekanth

**Comment by makitso** [comment]
Yes, that worked -- thanks!
